### PR TITLE
Fix minor issues

### PR DESCRIPTION
**Pull request by davidallendj**
This PR fixes a number of small issues such as `--cacert` not being available using the `serve` command, a type in the gorelease.yaml, and error messages being formatted incorrectly.

### CODE REVIEW

**Comment by synackd** [comment]
If `-c` is passed but the file doesn't exist, are default config values used? I did this and did not see an error that the config file did not exist.

**Comment by davidallendj** [comment]
> If `-c` is passed but the file doesn't exist, are default config values used? I did this and did not see an error that the config file did not exist.

Yes, that's how it works.

**Comment by synackd** [comment]
> > If `-c` is passed but the file doesn't exist, are default config values used? I did this and did not see an error that the config file did not exist.
> 
> Yes, that's how it works.

I think it might be helpful to fail quickly if the config file isn't found if passed explicitly, that way the user doesn't assume that their file is getting read and can quickly pinpoint that the path they provided doesn't exist (e.g. mistyped or old path).

**Comment by davidallendj** [comment]
Yeah, that makes sense. I'll add a check for that.

**Comment by synackd** [comment]
I don't see `lib/` anymore, so we can probably get rid of [this](https://github.com/OpenCHAMI/configurator/blob/2a9e7c72dc7aea8b12ff6289bc7acd8445514dec/.goreleaser.yaml#L48) line and [this](https://github.com/OpenCHAMI/configurator/blob/2a9e7c72dc7aea8b12ff6289bc7acd8445514dec/.goreleaser.yaml#L30) line. I get an error when building with them there:
```
  ⨯ release failed after 17s                         error=failed to find files to archive: globbing failed for pattern lib/: matching "./lib": file does not exist
```
also [this](https://github.com/OpenCHAMI/configurator/blob/2a9e7c72dc7aea8b12ff6289bc7acd8445514dec/Dockerfile#L12) line and optionally [this](https://github.com/OpenCHAMI/configurator/blob/2a9e7c72dc7aea8b12ff6289bc7acd8445514dec/Dockerfile#L5) one.

That will get it to build, then [this](https://github.com/OpenCHAMI/configurator/blob/2a9e7c72dc7aea8b12ff6289bc7acd8445514dec/Dockerfile#L14) line should be changed to
```Dockerfile
CMD ["/configurator/configurator"]
```
so the command works.

After all that, I can see the `serve` command.

```
# docker run --rm ghcr.io/openchami/configurator:v0.1.0
Tool for building common config files

Usage:
  configurator [flags]
  configurator [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  config      Create a new default config file
  fetch       Fetch a config file from a remote instance of configurator
  generate    Generate a config file from state management
  help        Help about any command
  inspect     Inspect generator plugin information
  serve       Start configurator as a server and listen for requests

Flags:
      --cacert string   path to CA cert. (defaults to system CAs)
  -c, --config string   set the config path (default "./config.yaml")
  -h, --help            help for configurator
  -v, --verbose         set to enable verbose output

Use "configurator [command] --help" for more information about a command.
```

**Review by synackd — APPROVED** [review]
I've tested building and running these with the deployment-recipes quickstart (https://github.com/OpenCHAMI/deployment-recipes/pull/92) and it is working.

**Pull request merged**
